### ISSUE TITLE
pipelineUnit example does not work with com.lesfurets:jenkins-pipeline-unit:1.1

### ISSUE THREAD

**Issue by sic-bre** [macg33zr/pipelineUnit#3]
I need some of the new features in JenkinsPipelineUnit 1.1 (e.g. Windows build support).  When using JenkinsPipelineUnit 0.12 your example works.  When I tried upgrading your example here by changing the dependency to "com.lesfurets:jenkins-pipeline-unit:1.1"  I get errors like the following.  I don't know spock well enough to debug what has changed.  Do you have any ideas?

```
Too few invocations for:

1 * shellMock.call(_) >> { args ->

            def shellCmd = args[0]
            assert shellCmd == GRADLE_EXPECTED_CMD
        }   (0 invocations)

Unmatched invocations (ordered by similarity):

None


Too few invocations for:

1 * shellMock.call(_) >> { args ->

            def shellCmd = args[0]
            assert shellCmd == GRADLE_EXPECTED_CMD
        }   (0 invocations)

Unmatched invocations (ordered by similarity):

None

	at org.spockframework.mock.runtime.InteractionScope.verifyInteractions(InteractionScope.java:78)
	at org.spockframework.mock.runtime.MockController.leaveScope(MockController.java:76)
	at tests.job.JenkinsfileTestSpec.Jenkinsfile should run gradle tests with expected command line validate:#P_VALIDATE gradle: #P_GRADLE_TASKS_OPTIONS(JenkinsfileTestSpec.groovy:24)
```

**Comment by macg33zr** [comment]
Thanks for the heads up. I have update the project to JenkinsPipelineUnit 1.1. There seemed to be a change in behaviour where the string parameter to a shell command like 'sh "foo var"' was passing the argument to the shell mock differently. I have made a change so the test works, but need to investigate this some more when I have time. Anyway, the regression file method of JenkinsPipelineUnit is normally sufficient for checking the shell command is as expected.

**Comment by sic-bre** [comment]
Please post to this ticket if you get an answer to this question as I'm quite interested in understanding how this plumbing works.  I'm just starting a project to convert my companies existing Jenkins Pipeline projects into using a unit and functional testing project.  They have grown enough that it will substantially improve our quality and productivity going forward.
