### ISSUE TITLE
Pass -Dpipeline.stack.write to tests to simplify updating the stack trackes.

### ISSUE THREAD

**Issue by sic-bre** [macg33zr/pipelineUnit#4]
When refreshing the pipeline testing output it be useful to add the following in the build.gradle to allow running doing a "gradle -Dpipeline.stack.write=true test --tests *" to refresh all the stack traces?

test {
    systemProperty "pipeline.stack.write", System.properties["pipeline.stack.write"]
}

**Comment by macg33zr** [comment]
I think I have merged / fixed it but please open this again if I haven't. See the gradle.properties file.
